export const celebratoryPhrases = [
  "You rock!!!",
  "Good jorb!!!",
  "Yeah baby!!!",
  "Ohhhh yeah!!!",
  "Woohoo!!!",
  "Yippee!!!",
  "Nice!!!",
  "Who's awesome? Yoose awesome!!!",
  "Boom Chaca Lacka!!!",
  "Ding Dong Baby!!!",
  "Namaste... Baby!!!",
  "whistle, whistle!!!",
  "that'll do pig, that'll do.",
  "Good Job. You are the best. Like really great. Super strong. Determined. Disciplined. Etcetera!!!",
];
